#!/bin/bash
#
#

BIN="/root/.pyenv/versions/3.5.2/bin/python3.5" 

DIR=$(cd `dirname $0`;echo $PWD)
CONF="$DIR/mongodb.py"
PROG="mongodb"

PID_FILE=/tmp/${PROG}.pid
LOG_FILE=/tmp/${PROG}.log

case $1 in 
	start)
		if [ -f $PID_FILE ];then
			echo "Maybe already running...! Pid file is: $PID_FILE"
			exit 2
		fi
		nohup $BIN $CONF > $LOG_FILE &
		if [ $? -eq 0 ];then
			PID=$(ps axu | grep 'python' | grep $PROG | grep -v grep | awk '{print $2}')
			echo $PID > $PID_FILE
		else
			echo "Error"
		fi
		;;
	stop)
		if [ ! -f $PID_FILE ];then
			echo "Maybe not run ! Pid file not find ($PID_FILE)"
			exit 2
		fi
		kill $(cat $PID_FILE) && rm -rf $PID_FILE
		;;
	*)
		echo "Usage:$0 {start|stop}"
esac
